(source gnu)
(source melpa-stable)

(depends-on "elixir-mode")
(depends-on "alchemist")
(depends-on "haskell-mode")
(depends-on "flycheck")
(depends-on "flycheck-haskell")
(depends-on "shm")
(depends-on "magit")