(source gnu)
(source melpa-stable)

(depends-on "elixir-mode")
(depends-on "alchemist")
(depends-on "haskell-mode")
(depends-on "flycheck")
(depends-on "flycheck-haskell")
(depends-on "shm")
(depends-on "magit")
(depends-on "yaml-mode")
(depends-on "material-theme" :git "https://github.com/cpaulik/emacs-material-theme")
(depends-on "tldr" :git "https://github.com/kuanyui/tldr.el")
(depends-on "markdown-mode")
(depends-on "slim-mode")