#+title: .emacs.d
#+date: <2016-02-10 Wed>
#+author: Sergei Maximov
#+email: s.b.maximov@gmail.com


My Emacs configuration.

* Things I use

  + package.el + req-package.el for managing packages.
  + company-mode for completion.
  + magit for interfacing with Git.
  + Org mode for notes and stuff.
  + flycheck for syntax checking.
  + projectile for project management.
  + ivy + counsel as generic completion backend.
  + swiper as an alternative to isearch.
  + yasnippet (custom [[snippets/][snippets]]).

* Prerequisites

** Lisp

*** [[https://github.com/cask/cask][Cask]]

Clone the repository:

#+begin_src bash
  $ git clone git@github.com:/cask/cask.git ~/.local/share/cask
#+end_src

Make a link to the executable appear somewhere on =PATH=:

#+begin_src bash
  $ cd ~/.local/bin
  $ ln -s ../share/cask/bin/cask cask
#+end_src

** Ruby

Install [[https://rvm.io][RVM]] to manage rubies.

*** Required gems:

- =rubocop= ::
     a static code analyzer enforcing guidelines outlined
     in the community Ruby Style Guide.
- =ruby-lint= ::
     another static code analyzer which focuses primarily
     on technical problems in your code.
- =pry= ::
     a ruby interactive REPL on steroids. =pry-doc= should
     be installed too. Required for the =robe= code assistant tool.
- =bundler= ::
     bundler manages an application's dependencies though its entire life.

** Markdown

Requires the =kramdown= gem to render markdown files.

** SCSS

Requires the =sass= gem to compile SASS/SCSS files.

** Rust

I prefer installing Rust via [[https://rustup.rs][Rustup]].

Installation locations:

- =CARGO_HOME= - =$XDG_CACHE_HOME/cargo=;
- =RUSTUP_HOME= - =$XDG_CACHE_HOME/rustup=.

Rust sources (required for Racer) are stored in
=~/src/rust=.

** ELM

You need to install following NPM packages:

- =elm= - ELM compiler and utilities;
- =elm-oracle= - a tool to query information about an ELM project's source code;
  used for completion.

* Licence

  Copyright © 2016 Sergei Maximov. Released under WTFTPL 2.0. See [[COPYING]].
